### ISSUE TITLE
Fluid events

### ISSUE THREAD

**Issue by johnfg2610** [SpongePowered/SpongeAPI#1580]
Hey,

So ive been working on a plugin and have noticed that fluids being placed(using buckets etc etc) dont seem to be recorded i was hoping for a FuildBlockChange event or something intergrated into the ChangeBlockEvent 

Thanks
Johnfg10

**Comment by parlough** [comment]
I believe this was fixed in https://github.com/SpongePowered/SpongeCommon/commit/e4438fd5ebc340a371c8b00f6c6a516584dcda38

Give it another go

**Comment by Deamon5550** [comment]
If its still an issue then reopen the issue in spongecommon, otherwise 👍
